services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    container_name: front
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerfileFrontend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - back

  back:
    container_name: back
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads

volumes:
  postgres_data:
    name: scint-db
  uploads_data:
    name: scint-uploads
