version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    container_name: front
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"

  back:
    container_name: back
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  postgres_data:
    name: scint-db
