version: '3.3'

services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=scint_ontu
      - POSTGRES_USER=scint_ontu_user
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  back:
    container_name: back
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:4000/v1/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://scint_ontu_user:postgres@db:5432/scint_ontu?schema=public"
    ports:
      - "9002:4000"
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads

  front:
    container_name: front
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8092:3000"
    depends_on:
      - back

volumes:
  postgres_data:
  uploads_data:
