services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  front:
    container_name: front
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - back

  back:
    container_name: back
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://scint_ontu_user:some-db-password-for-scint_ontu@db:5432/scint_ontu?schema=public"
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads

volumes:
  postgres_data:
    name: scint-db
  uploads_data:
    name: scint-uploads
